export interface DirectionList {
  name: string;
  technologies: string[];
  techIcons: string[];
}

export const technologiesData = [
  {
    category: "Software",
    directionList: [
      {
        name: "Mobile",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Services",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Websites",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Desktop",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Web3",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "AI",
        technologies: ["React", "PHP", "TypeScript", "Java"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
    ],
  },
  {
    category: "Hardware",
    directionList: [
      {
        name: "Param1",
        technologies: ["Param1", "Param2", "Param3"],
        techIcons: [
          "airtable.png",
          "asana.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",

          "hubspot.png",
          "intercom.png",
          "airtable-2.png",

          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Param2",
        technologies: ["Param1", "Param2", "Param3"],
        techIcons: [
          "intercom.png",
          "jira.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
        ],
      },
      {
        name: "Param3",
        technologies: ["Param1", "Param2", "Param3"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
    ],
  },
  {
    category: "S&H Systems",
    directionList: [
      {
        name: "Param1",
        technologies: ["Param1", "Param2", "Param3", "Param4"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
      {
        name: "Param2",
        technologies: ["Param1", "Param2", "Param3", "Param4"],
        techIcons: [
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "jira.png",
          "kafka.png",
          "lever.png",
          "marketo.png",
          "microsoft-azure.png",
          "mixpanel-1.png",
          "mixpanel.png",
          "ms-sql-1.png",
          "ms-sql.png",
          "oracle.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
          "airtable-2.png",
          "airtable.png",
          "asana.png",
          "hubspot.png",
          "intercom.png",
        ],
      },
    ],
  },
];
